### ISSUE TITLE
Every Component includes all scss content when using css module.

### ISSUE THREAD

**Issue by Jancat** [milad-alizadeh/vue-cli-plugin-scss-base#1]
My every component use css module:

```css
<style lang="scss" module>
.foo {}
</style>
```

And used in template:
```html
<template>
  <div :class="$style.foo"></div>
</template>
```

But I found in every **style** link, the all css rules in scss directory was included in single component css module.
**component A style**
![image](https://user-images.githubusercontent.com/11827786/44317640-eb875580-a464-11e8-8682-eefe2810f697.png)
**component B style**
![image](https://user-images.githubusercontent.com/11827786/44317651-f8a44480-a464-11e8-8374-1b5a24baca2a.png)

Is the configure reason that import `base.scss` in every css module?

```js
css: {
    loaderOptions: {
      sass: {
        data: '@import "@/scss/base.scss";',
      },
    },
  },
```

**Comment by milad-alizadeh** [comment]
Hi. Thank you for reporting this issue. As you have suspected the reason for this is `'@import "@/scss/base.scss";'`. This injects the base CSS and all mixins and variables to each component. If you run `yarn build` this wouldn't be an issue as the CSS gets extracted and will be injected only once, however. This is an issue while development and if you decide not to use extracted CSS option.
I have now created a fix for this by doing the following: 
The SCSS is now separated into two files `settings.scss` and `base.scss`. The `settings.scss` includes all variables and mixins which will be injected into each component using `vue.config.js`. The `base.scss` includes all the base CSS including reset, utilities, etc and will be injected only once in `App.vue`.  Please update to version 0.1.6 for these changes

**Comment by milad-alizadeh** [comment]
#

**Comment by Jancat** [comment]
@milad-alizadeh Thank you for solving the issue in time. I have updated to version 0.1.6 and that is ok!

**Comment by Jancat** [comment]
There seem to be a little issue.
I defined a scss function in **utillities.scss**:
```scss
@import 'u-visually-hidden';

@function slim-border($color: red) {
  @return 1px solid $color;
}
```

Then invoke the function in some components:
```scss
<style lang="scss" module>
.foo {
   border: slim-border();
}
</style>
```

But the `slime-border()` was not be compiled to css for the function not found:

![image](https://user-images.githubusercontent.com/11827786/44388678-469b7400-a55b-11e8-81f2-c5155304ae96.png)

The **utiltilties.scss** was imported in **base.scss**:
```
@import 'base/normalize';
@import 'base/form';
@import 'base/general';
@import 'base/global';

@import 'utilities/utilities';
@import 'animations/animations';
```

And **base.scss** was imported in **App.vue**
```
<style lang="scss">
@import '@/scss/base.scss';
</style>
```

I was confused why the scss function not be found?

Later I put the scss function into **_mixin.scss** and it works temporarily. Should there be a **functions.scss** file included in **settings.scss**?

@milad-alizadeh Do you have any idea?

**Comment by milad-alizadeh** [comment]
This behaviour is expected. The `_utilities.scss` is part of `base.scss` which is included only once in `App.vue`. That means the functions/variables in these files would not be available elsewhere apart from `App.vue`. In order to access it you need to reference this in `settings.scss` which is injected into each component. I have include a `_functions.scss` in settings in version 0.1.7 where you can include any custom functions.

That being said, utilities are not meant for registering custom functions. Utilities are simple classes that can be used to share multiple property without repeating code. For example with the example above, it can be rewritten as 
```
// utilities/_u-box.scss
.u-box {
   padding: 10px;
   max-width: 300px;
   border: 1px solid black
}
```
You can then use this class by directly referencing it in the HTML or use `@extend` to use it in your CSS.

**Comment by Jancat** [comment]
@milad-alizadeh Thanks for your patient answer. I learn it.

**Comment by milad-alizadeh** [comment]
Glad it's resolved :)
